# -*- coding: utf-8 -*-
"""Question 2 factwise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuJ4amc4Oyf0GYs46MpMndfQ2yLEmD7t
"""

