# -*- coding: utf-8 -*-
"""Question1_Factwise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N6BMOGNcdeODaYfqSrdzb_X3Vh8Ranax
"""

eg: [1,1,2]
output:k= 2 and [1,2]

a=input()
b=[int(num) for num in a.split(',')]
f=list(set(b))
k=len(f)
print(f'k={k}')
print(f)