# -*- coding: utf-8 -*-
"""Question 4 factwise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16JI87A3KiQd9ZJxgEyA0jYK7KnlqaAE9
"""

a=input()
t=input()
b=[int(i) for i in a.split(',')]
for i in b:
  if i==t:
    print(b[i])
  else:
    for j in b:
      if t>j:
        print(b[j]+1)