# -*- coding: utf-8 -*-
"""Question 3 FACTWISE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7hfZM9lN-rAY6BFpULMiJb-gXT7CW1H
"""

def profit(a):
  if len(a)<2:
    return 0

  minprice=a[0]
  maxprofit=0

  for price in a:
    pointer=int(price)-int(minprice)
    maxprofit=max(maxprofit,pointer)
    minprice=min(minprice,price)

  print(maxprofit)

a=input()
b=[int(i) for i in a.split(',')]
result=profit(b)